# Generated by Django 6.0.4 on 2026-04-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
    ]
